### ISSUE TITLE
SAM type instances with case class results get wrong indentation

### ISSUE THREAD

**Issue by howyp** [scalameta/scalafmt#1201]
- **Version**: 1.4.0
- **Integration**: IntelliJ
- **Configuration**:
```
maxColumn=120
style=defaultWithAlign
align=most
```

## Steps

Given code like this:
```scala
object Test {
  case class SomeCaseClass(first: String, second: String)

  trait CanBeSAMType { def go(x: String): SomeCaseClass }

  val isSAM: CanBeSAMType = x => SomeCaseClass(
    first = x, second = x
  )
}

```

When I run scalafmt by saving in IntelliJ

## Problem

Scalafmt formats code like this:
```scala
object Test {
  case class SomeCaseClass(first: String, second: String)

  trait CanBeSAMType { def go(x: String): SomeCaseClass }

  val isSAM: CanBeSAMType = x =>
    SomeCaseClass(
      first = x,
      second = x
  )
}
```

## Expectation

I would like the formatted output to look like this:
```scala
object Test {
  case class SomeCaseClass(first: String, second: String)

  trait CanBeSAMType { def go(x: String): SomeCaseClass }

  val isSAM: CanBeSAMType = x => SomeCaseClass(
    first = x,
    second = x
  )
}
```

or like this:
```scala
object Test {
  case class SomeCaseClass(first: String, second: String)

  trait CanBeSAMType { def go(x: String): SomeCaseClass }

  val isSAM: CanBeSAMType = x =>
    SomeCaseClass(
      first = x,
      second = x
    )
}
```

## Notes

The dangling parenthesis seems to be indented wrongly.

**Comment by olafurpg** [comment]
Thanks for reporting! Have you tried the latest release? This should be fixed

**Comment by howyp** [comment]
Oh, I didn't realise there was a new release of IntelliJ, which I needed before I got the new version of the plugin.

I've upgraded to 1.5.1 and I'm afraid I still see the issue, though 🤨

**Comment by howyp** [comment]
Awesome, thanks for such a quick response 👍
