### ISSUE TITLE
scalafmt does not work with IntelliJ

### ISSUE THREAD

**Issue by nikoplusx** [scalameta/scalafmt#2711]
- **plugin version**: 2.4.3
- **core version**: 3.0.1
-  **platform**: Ubuntu 20.4
- **Integration**: IntelliJ 2021.2.1
- **Configuration**:
```
version = 3.0.1

align.preset = more    
maxColumn = 80 
```

## Steps
1. Add plugin to plugins.sbt
`addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.3")`

my entire `plugins.sbt`
```
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.6")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M9")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.3")
addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.19.0")
```

You can see that the plugin for resolving dependencies from s3 and the coursier plugin are present

2. Configure scalafmt as the main formatter in the IntelliJ settings
3. Try to format the code using the keymap shortcut

## Problem
Using the automatic format I am prompted with the message 
```
Scalafmt version `3.0.1` is not downloaded yet. Would you like to to download it?
```
Clicking on `Download` I get
```
Can not resolve scalafmt version 3.0.1: An error occurred during downloading: unresolved dependency: com.martiansoftware#nailgun-server;0.9.1: several problems occurred while resolving dependency: com.martiansoftware#nailgun-server;0.9.1 {compile=[compile(*), master(*)], runtime=[runtime(*)]}: several problems occurred while resolving dependency: com.martiansoftware#nailgun-all;0.9.1 {}: company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3 company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.pom: java.net.MalformedURLException: unknown protocol: s3 company_name s3 releases: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/releases/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.pom: java.net.MalformedURLException: unknown protocol: s3 Local cache: unable to get resource for com.martiansoftware#nailgun-all;0.9.1: res=file:///home/niko/.ivy2/cache: java.io.IOException: Downloaded file size doesn't match expected Content Length for file:/home/niko/.ivy2/cache. Please retry. company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3 company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3 company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-server;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-server/0.9.1/nailgun-server-0.9.1.pom: java.net.MalformedURLException: unknown protocol: s3 company_name s3 releases: unable to get resource for com/martiansoftware#nailgun-server;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/releases/com/martiansoftware/nailgun-server/0.9.1/nailgun-server-0.9.1.pom: java.net.MalformedURLException: unknown protocol: s3 Local cache: unable to get resource for com.martiansoftware#nailgun-server;0.9.1: res=file:///home/niko/.ivy2/cache: java.io.IOException: Downloaded file size doesn't match expected Content Length for file:/home/niko/.ivy2/cache. Please retry. several problems occurred while resolving dependency: com.martiansoftware#nailgun-all;0.9.1 {}: company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3 company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.pom: java.net.MalformedURLException: unknown protocol: s3 company_name s3 releases: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/releases/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.pom: java.net.MalformedURLException: unknown protocol: s3 Local cache: unable to get resource for com.martiansoftware#nailgun-all;0.9.1: res=file:///home/niko/.ivy2/cache: java.io.IOException: Downloaded file size doesn't match expected Content Length for file:/home/niko/.ivy2/cache. Please retry. company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3 company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3 several problems occurred while resolving dependency: com.martiansoftware#nailgun-all;0.9.1 {}: company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3 company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.pom: java.net.MalformedURLException: unknown protocol: s3 company_name s3 releases: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/releases/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.pom: java.net.MalformedURLException: unknown protocol: s3 Local cache: unable to get resource for com.martiansoftware#nailgun-all;0.9.1: res=file:///home/niko/.ivy2/cache: java.io.IOException: Downloaded file size doesn't match expected Content Length for file:/home/niko/.ivy2/cache. Please retry. company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3 company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3
```

It seems like IntelliJ is trying to download the plugin from somewhere and since it does not find it there is tries to use the resolvers defined in my `build.sbt`.  But anyway it will not find anything there since these resolvers point to s3 buckets only containing my published libraries...

I tried to install the plugin manually but  this did not work. I mean that I tried to download the IntelliJ plugin zip from the official website and import it as a plugin.

## Expectation
I would expect that IntelliJ is able to download the formatter and apply the format?

## Workaround

The only way to make it run is by using scalafmt from the command line as an sbt goal: `sbt scalafmt`

**Comment by tgodzik** [comment]
Thanks for reporting! If it is only broken in the Intellij Scala plugin I would suggest reporting it first in https://youtrack.jetbrains.com/issues/SCL 

As a workaround, you could also try commenting the S3 config, reimproting the build, downloading scalafmt. 

Not sure exactly what might be causing the issue exactly, but maybe Intellij's team might know the answer.

**Comment by nikoplusx** [comment]
Thank you for your response. I commented out the s3 config and the s3 resolver from the plugins but I am still getting the same error. I will also report it on the JetBrains tracker.

**Comment by kitbellew** [comment]
@unkarjedy could possibly help. this is not a scalafmt problem as scalafmt hadn't even been downloaded yet.

**Comment by nikoplusx** [comment]
btw everything works like a charm from the console. `sbt scalafmt` works without any issues.

**Comment by unkarjedy** [comment]
It should be fixed in https://youtrack.jetbrains.com/issue/SCL-16345 so I suppose this can be closed

> Please, ensure that you have the latest Scala Plugin version (2021.2.17) and tell if it helps.

**Comment by tgodzik** [comment]
Cool! Great to hear.

**Comment by nikoplusx** [comment]
I upgraded to the latest Scala plugin
![image](https://user-images.githubusercontent.com/64786344/131394678-b6e47c33-4c5b-4b03-82f6-f0390b6319dc.png)
and I am still getting the same error
```

Can not resolve scalafmt version 3.0.1: An error occurred during downloading: unresolved dependency: com.martiansoftware#nailgun-server;0.9.1: several problems occurred while resolving dependency: com.martiansoftware#nailgun-server;0.9.1 {compile=[compile(*), master(*)], runtime=[runtime(*)]}: several problems occurred while resolving dependency: com.martiansoftware#nailgun-all;0.9.1 {}: company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3 company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.pom: java.net.MalformedURLException: unknown protocol: s3 company_name s3 releases: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/releases/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.pom: java.net.MalformedURLException: unknown protocol: s3 Local cache: unable to get resource for com.martiansoftware#nailgun-all;0.9.1: res=file:///home/niko/.ivy2/cache: java.io.IOException: Downloaded file size doesn't match expected Content Length for file:/home/niko/.ivy2/cache. Please retry. company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3 company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3 company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-server;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-server/0.9.1/nailgun-server-0.9.1.pom: java.net.MalformedURLException: unknown protocol: s3 company_name s3 releases: unable to get resource for com/martiansoftware#nailgun-server;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/releases/com/martiansoftware/nailgun-server/0.9.1/nailgun-server-0.9.1.pom: java.net.MalformedURLException: unknown protocol: s3 Local cache: unable to get resource for com.martiansoftware#nailgun-server;0.9.1: res=file:///home/niko/.ivy2/cache: java.io.IOException: Downloaded file size doesn't match expected Content Length for file:/home/niko/.ivy2/cache. Please retry. several problems occurred while resolving dependency: com.martiansoftware#nailgun-all;0.9.1 {}: company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3 company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.pom: java.net.MalformedURLException: unknown protocol: s3 company_name s3 releases: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/releases/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.pom: java.net.MalformedURLException: unknown protocol: s3 Local cache: unable to get resource for com.martiansoftware#nailgun-all;0.9.1: res=file:///home/niko/.ivy2/cache: java.io.IOException: Downloaded file size doesn't match expected Content Length for file:/home/niko/.ivy2/cache. Please retry. company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3 company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3 several problems occurred while resolving dependency: com.martiansoftware#nailgun-all;0.9.1 {}: company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3 company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.pom: java.net.MalformedURLException: unknown protocol: s3 company_name s3 releases: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/releases/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.pom: java.net.MalformedURLException: unknown protocol: s3 Local cache: unable to get resource for com.martiansoftware#nailgun-all;0.9.1: res=file:///home/niko/.ivy2/cache: java.io.IOException: Downloaded file size doesn't match expected Content Length for file:/home/niko/.ivy2/cache. Please retry. company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3 company_name s3 snapshots: unable to get resource for com/martiansoftware#nailgun-all;0.9.1: res=s3://s3-eu-west-1.amazonaws.com/company_name-m2-repository/snapshots/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.jar: java.net.MalformedURLException: unknown protocol: s3
```

so I hope you will not close this yet

**Comment by nikoplusx** [comment]
@tgodzik Could you please reopen the issue?

**Comment by kitbellew** [comment]
@nikoplusx what would you like us to do, by reopening a ticket? is there any reason to believe it's in scalafmt and not in intellij?

**Comment by nikoplusx** [comment]
I think that a coordinated effort would be more efficient than just delegating the issue to the IntelliJ team. If you think that there's no issue with scalafmt then keep the issue closed.

**Comment by tgodzik** [comment]
Let's keep this closed, I will follow the other issue on youtrack and provide assistance if needed there.

**Comment by nikoplusx** [comment]
For anyone facing the same problem with an s3 sbt resolver here's a workaround till they fix the bug
https://youtrack.jetbrains.com/issue/SCL-16345#focus=Comments-27-5156528.0-0

**Comment by unkarjedy** [comment]
FTR feature ticket: [scalafmt: support resolving from AWS S3 repository](https://youtrack.jetbrains.com/issue/SCL-19488)
