### ISSUE TITLE
Scalafmt doesn't handle 2.12.2 syntax for commas at the end of a multi-line list

### ISSUE THREAD

**Issue by lespea** [scalameta/scalafmt#909]
This template is a guideline, not a strict requirement.
- **Version**: 0.6.8
- **Integration**: IntelliJ / console tool
- **Configuration**: any

## Steps
Having a comma in the last item of a list (spanning multiple lines) is now valid syntax in scala 2.12.2.  Scalafmt doesn't seem to support this and throws this exception: `illegal start of simple expression`.

```
# cat t.scala
object Test {
  val a = Seq(
    1,
    2,
    3,
  )
}
# scalac -version
Scala compiler version 2.12.2 -- Copyright 2002-2017, LAMP/EPFL and Lightbend, Inc.
# scalac t.scala
# scalafmt
[warn] Error in .../t.scala: <input>:6: error: illegal start of simple expression
)
    ^
```

## Expectations
Scalafmt handles this syntax

## Wishlist
It would also be cool if there was a config option to force all lists to include a comma on the last item.

**Comment by olafurpg** [comment]
Thank you for reporting! This should actually be easy to accommodate, I added support for parsing trailing commas in scala.meta (https://github.com/scalameta/scalameta/pull/660) as soon as they got merged into scala/scala. I am very excited to use them myself :)

I agree that it would be nice to have a flag to insert them where appropriate (e.g. in config style only). That should totally be doable!

**Comment by mushtaq** [comment]
+1

**Comment by lespea** [comment]
Any update on this?

**Comment by olafurpg** [comment]
I am currently swamped with tasks in scalameta+scalafix, so I haven't had much bandwidth to work on scalafmt lately. All the pieces for this issue are already in place, the only thing missing is to add support to use a `scala.meta.Dialect` that supports trailing commas. The current supported dialects are here https://github.com/scalameta/scalafmt/blob/d5c3b0a14c8abb0f6afb9d95b50a67856afd9dba/scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfDecoders.scala#L27-L28
 I believe we need to add another case for Scala212 where
```scala
val Scala212 = scala.meta.dialects.Scala212.copy(allowTrailingCommas = true) // we forgot to change in last 1.7 release
```

**Comment by olafurpg** [comment]
I don't have the luxury to work with 2.12-only projects (only cross 2.11/2.12 even 2.10) so trailing commas haven't hit my day to day workflow yet 😄

**Comment by olafurpg** [comment]
BTW, I implemented a while ago a rewrite to insert trailing commas where they might make sense https://github.com/olafurpg/scalafix/commit/21e35a3bf5fdae3182102151407599a1636f88f1#diff-601bbf131241a9bce3e6683e6143eb83R17 Here's a diff from running it https://github.com/olafurpg/scala-repos/pull/19 We could probably add that as a `rewrite.rules = [UseTrailingCommas]` to force usage of trailing commas in for example config style

**Comment by lespea** [comment]
Cool.  It obviously isn't a showstopper or anything I was just curious.  Thanks for the update :)

**Comment by olafurpg** [comment]
This got fixed in #979

**Comment by mjaghouri** [comment]
This still fails if there a comment on the line after the trailing comma.
```
object Test {
  val a = Seq(
    1,
    2,
    3,  // this comment makes formatting fail
  )
}
```

**Comment by gabro** [comment]
@mjaghouri just stumbled upon this ticket and the error you were seeing was a Scalameta parser bug, that recently got fixed (https://github.com/scalameta/scalameta/pull/1532). The upcoming Scalafmt 1.6 will handle that case too.

**Comment by olafurpg** [comment]
It can already be tested in 1.6.0-RC1
