### ISSUE TITLE
Errors running scalafmt via vim-autoformat plugin 

### ISSUE THREAD

**Issue by richashworth** [scalameta/scalafmt#931]
- **Version**: scalafmt 0.7.0-RC1
- **Integration**: vim-autoformat
- **Configuration**:
```
maxColumn = 100
```

## Steps

My .vimrc contains the following configuration:

```bash
" scalafmt settings
let g:formatdef_scalafmt = "'scalafmt --stdin'"
let g:formatters_scala = ['scalafmt']
let g:autoformat_verbosemode=1 " for error messages
let g:autoformat_autoindent = 0
let g:autoformat_retab = 0
let g:autoformat_remove_trailing_spaces = 0"
noremap <localleader>f :Autoformat<CR>
```

## Problem
Running `:Autoformat` produces the following messages:

```bash
Using python 2 code...
Formatter scalafmt has errors: ^[[2K Skipping.
Failing config: 'scalafmt --stdin'
Definition in 'g:formatdef_scalafmt' was unsuccessful.
No format definitions were successful.
Press ENTER or type command to continue
```

## Expectation

I would like the formatted output to replace the contents of the current buffer.

Is there something missing from my configuration, or a known workaround for this issue?

**Comment by pjrt** [comment]
I can't reproduce this. It formatted fine for me. Can you run `scalafmt` normally? 

If so, can you try `echo <path/to/scala/file.scala> | scalafmt --stdin`?

**Comment by richashworth** [comment]
Yes, running scalafmt normally works fine. Running `cat <filename> | scalafmt --stdin` works as well. I'm assuming this must be some issue with my vim setup...

**Comment by pjrt** [comment]
I guess. I do remember having issues getting auto-format to work the first time I tried to add scalafmt, but I can't remember how I fixed it. 

Would be great if it told you what "Formatter scalafmt has errors:" means.

**Comment by richashworth** [comment]
@pjrt thanks, I'm still having trouble with this. Is there any chance you could share your vim config / installed plugins for me to compare with?

**Comment by richashworth** [comment]
I think the issue is that the control characters `^[[2K` are getting prepended to the output of scalafmt. For example, when I run this without using vim-autoformat on a file that starts 

`package com.richashworth`, 

the results is:

`^[[2Kpackage com.richashworth`

I am able to get this with the following in my `.vimrc`:
```
noremap <localleader>f :% !scalafmt --stdin<CR>
```

Is there any way to prevent scalafmt returning these control codes in the response?

**Comment by pjrt** [comment]
@richashworth 
I really don't know what that can be about. Here's my vimrc:

https://github.com/pjrt/dotfiles/blob/master/vimrc#L221-L223

I wonder, what terminal emulator are you using? Or are you running something like gvim or Macvim?

**Comment by richashworth** [comment]
Thanks. I'm using terminal vim (installed with homebrew), in iTerm2.

**Comment by reuben-sutton** [comment]
I also get this with neoformat - I fixed it temporarily by performing a substitute on the results of the command: ```let stdout = split(substitute(system(cmd.exe, stdin), ".[2K", "", ""), '\n')```

**Comment by richashworth** [comment]
An alternative solution using nailgun has been suggested in https://github.com/Chiel92/vim-autoformat/issues/184#issuecomment-306591247 by @HHammond. There does still appear to be an underlying issue with scalafmt, though.

**Comment by olafurpg** [comment]
Closing due to inactivity, I haven't used the vim integration for a long time. Would love a PR updating the docs to reflect what is the best setup today :)

**Comment by kinowarrior** [comment]
Same issue - April 2019. Any progress?

**Comment by lJoublanc** [comment]
Currently this is failing due to the `Formatting ...` message that's printed out.
Would it be possible to suppress this when `--quiet` is passed as an argument?
